Repository kubernetes-sigs/cloud-provider-baiducloud, pull requests merged in 2019-01, with the labels that each got.

#30 add router info on node
  pkg/cloud-provider/cce.go
  pkg/cloud-provider/options.go
  pkg/cloud-provider/routes.go
Labels: area/VPC, kind/feature

#32 增加中文文档
  docs/tutorial_zh-CN.md
Labels: area/Doc

#33 query BLB id
  docs/tutorial_zh-CN.md
Labels: area/BLB

#35 fix ineffectual assignment to err, typo fixed and simple code
  pkg/sdk/bcc/cds.go
  pkg/sdk/bce/core.go
  pkg/sdk/bos/bucket.go
  pkg/sdk/util/util.go
Labels: lgtm
