Repository kubernetes-sigs/cloud-provider-baiducloud, pull requests merged in 2019-05, with the labels that each got.

#72 update doc
  README.md
  docs/master-tutorial_zh-CN.md
  docs/release-tutorial_zh-CN.md
  docs/tutorial_zh-CN.md
Labels: area/Doc

#75 fix: support subnet-id in annotation and random select vm
  docs/controllers/service/annotations.md
  docs/controllers/service/examples/nginx-BLB-subnet-id.yaml
  docs/tutorial_zh-CN.md
  pkg/cloud-provider/load_balancer_blb.go
  pkg/cloud-provider/load_balancer_vpc.go
  pkg/cloud-provider/options.go
  pkg/cloud-provider/options_test.go
Labels: approved, lgtm

#79 fix blb exact match issue
  pkg/cloud-provider/cce.go
  pkg/cloud-provider/cidr_test.go
  pkg/cloud-provider/load_balancer_blb.go
  pkg/cloud-provider/load_balancer_blb_listener.go
  pkg/cloud-provider/load_balancer_util.go
  pkg/cloud-provider/options_test.go
  pkg/cloud-provider/routes.go
  pkg/cloud-sdk/blb/loadbalancer.go
Labels: area/BLB, kind/bug

#81 solve issue#70"指定LB Service的BLB?"
  docs/controllers/service/examples/nginx-BLB-assigned.yaml
  docs/tutorial_zh-CN.md
  pkg/cloud-provider/load_balancer.go
  pkg/cloud-provider/load_balancer_blb.go
  pkg/cloud-provider/load_balancer_blb_backend_server.go
  pkg/cloud-provider/load_balancer_eip.go
  pkg/cloud-provider/load_balancer_util.go
  pkg/cloud-provider/options.go
Labels: approved, area/BLB, kind/feature, lgtm

#86 fix renaming blb bug & retry to create lb.desc
  pkg/cloud-provider/load_balancer.go
  pkg/cloud-provider/load_balancer_blb.go
  pkg/cloud-provider/load_balancer_eip.go
  pkg/cloud-sdk/blb/loadbalancer.go
Labels: approved, lgtm

#90 small modify
  pkg/cloud-provider/load_balancer.go
  pkg/cloud-provider/load_balancer_blb.go
  pkg/cloud-provider/load_balancer_eip.go
Labels: approved, lgtm

#92 add testing case
  docs/controllers/service/examples/nginx-BLB-assignedID-EIP.yaml
  docs/controllers/service/examples/nginx-BLB-assignedID.yaml
  test/feature-test/run.sh
Labels: approved, lgtm
